### ISSUE TITLE
Fix the Home page UI for better functionability

### ISSUE THREAD

**Issue by sambitsingha** [cropsync/CropSync#15]
- The frontend part of this website lacks some functionability like for example - the oversized navbar icons and link, the background image doesn't create the basic UI look with the current webpage.
- Similarly , the footer needs to be changed , and it should be same in other pages if added .
- Also , the font needs to be updated.

I can work on this issue. Thank You

**Comment by KrishGaur1354** [comment]
Assigned >_<
