### ISSUE TITLE
Create a overlay for the header so that it doesn't hover over other items 

### ISSUE THREAD

**Issue by KrishGaur1354** [cropsync/CropSync#5]
Problem:
The current header implementation hovers over other items on the page, causing a visual obstruction and affecting the overall user experience. To address this, we need to implement an overlay for the header.

Proposed Solution:
Create a translucent overlay for the header that prevents it from overlapping with other items on the page. This overlay should be visually appealing and ensure that the header remains distinct without obstructing the content underneath.

Steps to reproduce:
Navigate to any page with content.
Observe the header overlapping with other elements.

Expected Behavior:
The header should have a translucent overlay that prevents it from hovering over other items on the page, ensuring a clean and unobstructed view of the content.

**Comment by adisuyash** [comment]
can I work on this issue ?

**Comment by KrishGaur1354** [comment]
> can I work on this issue ?

yeah, sure. Assigned to you.

**Comment by ayann07** [comment]
Please assign me this task. I will be doing this under KWOC 2023.

**Comment by adisuyash** [comment]
Sorry for my inactivity, i was busy in my college exams, but I'll finish this asap

**Comment by KrishGaur1354** [comment]
This is issue has been completed! >_<

by @adisuyash

**Comment by adisuyash** [comment]
> This is issue has been completed! >_<
> 
> by @adisuyash 
It was an easy one
Just I wasn't free 😂

I'm looking forward to contribute to KWoC?
Any updates regarding that ?
